language: node_js

node_js:
  - "7.2.0"

install:
  - npm install

script:
  - npm run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  target_branch: master
  keep-history: true
  on:
    branch: master

branches:
  only:
  - master
  - /^greenkeeper/.*$/
